require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

project 'EveryonesRefrigerator.xcodeproj'

target 'EveryonesRefrigerator' do
  config = use_native_modules!
  pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"], 'Flipper' => '0.171.1', 'Flipper-Folly' => '= 2.6.10', 'Flipper-RSocket' => '= 1.4.3'),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )

  target 'EveryonesRefrigeratorTests' do
    inherit! :complete
    # Pods for testing
  end

  ENVFILES = {
    'debug' => '$(PODS_ROOT)/../../env/.env.debug',
    'staging' => '$(PODS_ROOT)/../../env/.env.staging',
    'release' => '$(PODS_ROOT)/../../env/.env.production',
  }

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end

    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'ImageNotification' do
  pod 'Firebase/Messaging', '~> 8.15.0' # eg 6.31.0
end
