name: CI_CHECK_CHANGED_NATIVE
on:
  pull_request:
    branches:
      - main
jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Diff Native
        run: |
          git fetch origin ${GITHUB_BASE_REF}
          DIFF=$(git diff --name-only origin/${GITHUB_BASE_REF})
          for diff in $DIFF
          do
            if [[ $diff == *android* ]] || [[ $diff == *ios* ]]
            then
              exit 1
            fi
          done
